/////////////////////////////////////////////////////////////////////////////
// Name:        jbselftest.cpp
// Purpose:     Selftests for Sha256 & Twofish
// Author:      Jan Buchholz
// Created:     2026-04-03
// Changed:     2026-04-06
/////////////////////////////////////////////////////////////////////////////

#include "jbselftest.h"
#include "jbsha.h"
#include "jbtwofish.h"
#include "jbhmac.h"

JBSelfTest::JBSelfTest() {}

bool JBSelfTest::sha256Selftest() { //generated by Copilot
    JBSha sha;
    struct TestVector256 {
        std::string input;
        std::vector<uint8_t> expected;
    };
    const std::vector<TestVector256> tests = {
        // 1) empty string
        {
            "",
            {
                0xe3,0xb0,0xc4,0x42,0x98,0xfc,0x1c,0x14,
                0x9a,0xfb,0xf4,0xc8,0x99,0x6f,0xb9,0x24,
                0x27,0xae,0x41,0xe4,0x64,0x9b,0x93,0x4c,
                0xa4,0x95,0x99,0x1b,0x78,0x52,0xb8,0x55
            }
        },
        // 2) "abc"
        {
            "abc",
            {
                0xba,0x78,0x16,0xbf,0x8f,0x01,0xcf,0xea,
                0x41,0x41,0x40,0xde,0x5d,0xae,0x22,0x23,
                0xb0,0x03,0x61,0xa3,0x96,0x17,0x7a,0x9c,
                0xb4,0x10,0xff,0x61,0xf2,0x00,0x15,0xad
            }
        },
        // 3) long test string
        {
            "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
            {
                0x24,0x8d,0x6a,0x61,0xd2,0x06,0x38,0xb8,
                0xe5,0xc0,0x26,0x93,0x0c,0x3e,0x60,0x39,
                0xa3,0x3c,0xe4,0x59,0x64,0xff,0x21,0x67,
                0xf6,0xec,0xed,0xd4,0x19,0xdb,0x06,0xc1
            }
        }
    };
    for (const auto& t : tests) {
        std::vector<uint8_t> input(t.input.begin(), t.input.end());
        if (sha.computeSha256(input) != t.expected)
            return false;
    }
    return true;
}

bool JBSelfTest::pbkdf2HmacSha256Selftest() { //generated by Copilot
    struct TestVector {
        std::string password;
        std::string salt;
        uint32_t iterations;
        size_t dkLen;
        std::vector<uint8_t> expected;
    };
    std::vector<TestVector> tests = {
        {
            "password", "salt", 1, 32,
            {
                0x12,0x0f,0xb6,0xcf,0xfc,0xf8,0xb3,0x2c,
                0x43,0xe7,0x22,0x52,0x56,0xc4,0xf8,0x37,
                0xa8,0x65,0x48,0xc9,0x2c,0xcc,0x35,0x48,
                0x08,0x05,0x98,0x7c,0xb7,0x0b,0xe1,0x7b
            }
        },
        {
            "password", "salt", 2, 32,
            {
                0xae,0x4d,0x0c,0x95,0xaf,0x6b,0x46,0xd3,
                0x2d,0x0a,0xdf,0xf9,0x28,0xf0,0x6d,0xd0,
                0x2a,0x30,0x3f,0x8e,0xf3,0xc2,0x51,0xdf,
                0xd6,0xe2,0xd8,0x5a,0x95,0x47,0x4c,0x43
            }
        },
        {
            "password", "salt", 4096, 32,
            {
                0xc5,0xe4,0x78,0xd5,0x92,0x88,0xc8,0x41,
                0xaa,0x53,0x0d,0xb6,0x84,0x5c,0x4c,0x8d,
                0x96,0x28,0x93,0xa0,0x01,0xce,0x4e,0x11,
                0xa4,0x96,0x38,0x73,0xaa,0x98,0x13,0x4a
            }
        }
    };
    for (const auto& tv : tests) {
        std::vector<uint8_t> pw(tv.password.begin(), tv.password.end());
        std::vector<uint8_t> sa(tv.salt.begin(), tv.salt.end());
        auto result = JBHmac::pbkdf2HmacSha256(pw, sa, tv.iterations, tv.dkLen);
        if (result != tv.expected) {
            return false;
        }
    }
    return true;
}

bool JBSelfTest::twofishStandardSelftest() { // test vectors from www.schneier.com
    const std::vector<uint8_t> ct49 = {
        0x37, 0xfe, 0x26, 0xff, 0x1c, 0xf6, 0x61, 0x75,
        0xf5, 0xdd, 0xf4, 0xc3, 0x3b, 0x97, 0xa2, 0x05
    };
    constexpr int rounds = 49;
    std::vector<uint8_t> key(TWOFISH_KEY_SIZE, 0);
    std::vector<uint8_t> pt(TWOFISH_BLOCK_SIZE, 0);
    std::vector<uint8_t> ptx(TWOFISH_BLOCK_SIZE, 0);
    std::vector<uint8_t> ct(TWOFISH_BLOCK_SIZE, 0);
    for (int i = 1; i <= rounds; i++) {
        JBTwofish tf(key);
        ptx = pt;
        tf.encryptBase(pt);
        ct = pt;
        tf.decryptBase(pt);
        if (pt != ptx) return false;
        for (int j = 16; j < TWOFISH_KEY_SIZE; j++) key[j] = key[j - 16];
        for (int j = 0; j < TWOFISH_BLOCK_SIZE; j++) key[j] = ptx[j];
        pt = ct;
    }
    return ct == ct49;
}

bool JBSelfTest::twofishECBSelftest() {
    const std::vector<uint8_t> pln(plainText.begin(), plainText.end());
    JBTwofish tf(plnKey);
    std::vector<uint8_t> enc = tf.encryptECB(pln);
    std::vector<uint8_t> dec = tf.decryptECB(enc);
    return dec == pln;
}

bool JBSelfTest::twofishCBCSelftest() {
    const std::vector<uint8_t> ivec = { 0x01, 0xaa, 0xff, 0x55, 0x23, 0x91, 0x45, 0xee };
    const std::vector<uint8_t> pln(plainText.begin(), plainText.end());
    JBTwofish tf(plnKey);
    std::vector<uint8_t> enc = tf.encryptCBC(pln, ivec);
    std::vector<uint8_t> dec = tf.decryptCBC(enc, ivec);
    return dec == pln;
}

bool JBSelfTest::doAllTests() {
    bool b = sha256Selftest() &&
        pbkdf2HmacSha256Selftest() &&
        twofishStandardSelftest() &&
        twofishECBSelftest() &&
        twofishCBCSelftest();
    return b;
}

